module.exports = {
    "New York":    ["JFK", "LGA", "EWR"],
    "Los Angeles": ["LAX", "BUR", "SNA", "LGB"],
    "Chicago":     ["ORD", "MDW"],
    "San Francisco": ["SFO", "OAK", "SJC"],
    "Miami": ["MIA", "FLL", "PBI"],
    "Las Vegas": ["LAS", "VGT"],
    "Seattle": ["SEA", "BFI"],
    "Boston": ["BOS", "BED", "ORH"],
    "San Diego": ["SAN", "MYF"],
    "Orlando": ["MCO", "SFB"],
    "Denver": ["DEN", "APA"],
    "Phoenix": ["PHX", "AZA"],
    "Dallas": ["DFW", "DAL"],
    "Houston": ["IAH", "HOU"],
    "Atlanta": ["ATL", "PDK"],
    "Detroit": ["DTW", "DET"],
    "Minneapolis": ["MSP", "MIC"],
    "Philadelphia": ["PHL", "PNE"],
    "Charlotte": ["CLT", "JQF"],
    "Portland": ["PDX", "TTD"],
    "Honolulu": ["HNL", "HIO"],
    // europe
    "London": ["LHR", "LGW", "LCY"],
    "Paris": ["CDG", "ORY"],
    "Frankfurt": ["FRA", "HHN"],
    "Amsterdam": ["AMS", "RTM"],
    "Madrid": ["MAD", "TOJ"],
    "Barcelona": ["BCN", "GRO"],
    "Rome": ["FCO", "CIA"],
    "Milan": ["MXP", "BGY"],
    "Munich": ["MUC", "EDM"],
    "Zurich": ["ZRH", "BSL"],
    "Vienna": ["VIE", "GRZ"],
    "Dublin": ["DUB", "ORK"],
    "Lisbon": ["LIS", "FAO"],
    "Stockholm": ["ARN", "BMA"],
    "Oslo": ["OSL", "TRF"],
    "Copenhagen": ["CPH", "RKE"],
    "Helsinki": ["HEL", "EFHF"],
    "Moscow": ["SVO", "DME"],
    "Istanbul": ["IST", "SAW"],
    "Athens": ["ATH", "LGAT"],
    "Warsaw": ["WAW", "WMI"],
    "Prague": ["PRG", "LKPR"],
    "Budapest": ["BUD", "LHBP"],
    "Bucharest": ["OTP", "BBU"],
    "Sofia": ["SOF", "LBSF"],
    "Belgrade": ["BEG", "LYBE"],
    "Zagreb": ["ZAG", "LDZA"],
    "Ljubljana": ["LJU", "LJLJ"],
    "Varna": ["VAR", "LBWN"],
};