name: CI/CD

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: admin123
          MYSQL_DATABASE: airscan_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Wait for MySQL to be ready
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          # Loop until we can successfully connect
          until mysql -h 127.0.0.1 -u root -padmin123 -e "SELECT 1"; do
            echo "Waiting for MySQL to be ready..."
            sleep 3
          done

      - name: Create test database
        run: |
          mysql -h 127.0.0.1 -u root -padmin123 -e "CREATE DATABASE IF NOT EXISTS airscan_db;"

      - name: Install dependencies
        run: npm install

      # If you have any build step (e.g. React front-end), add it here
      # - name: Build
      #   run: npm run build

      - name: Run integration tests
        # Provide environment variables that your code expects
        env:
          DB_NAME: airscan_db
          DB_USER: root
          DB_PASS: admin123
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          JWT_SECRET: some_test_jwt_secret_key
          PORT: 3000  # or whatever port you want your app to run on
        run: |
          # The following will:
          # 1) Connect to MySQL at 127.0.0.1 with the given user/password
          # 2) syncDatabase() or seed if your startup logic does that automatically
          # 3) Then run the tests
          npm test
