name: CI/CD

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASS }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Wait for MySQL to be ready
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          # Loop until we can successfully connect
          until mysql -h 127.0.0.1 -u root -p{{ secrets.DB_PASS }} -e "SELECT 1"; do
            echo "Waiting for MySQL to be ready..."
            sleep 3
          done

      - name: Create test database
        run: |
          mysql -h 127.0.0.1 -u root -padmin123 -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_NAME }};"

      - name: Install dependencies
        run: npm install
        
      - name: Run integration tests
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: root
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        run: |
          # The following will:
          # 1) Connect to MySQL at 127.0.0.1 with the given user/password
          # 2) syncDatabase() or seed if your startup logic does that automatically
          # 3) Then run the tests
          npm test
