name: CI/CD

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASS }}         # admin123
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}                # airscan_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Wait for MySQL to be ready
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          until mysql -h 127.0.0.1 -u root -p${{ secrets.DB_PASS }} -e "SELECT 1" ; do
            echo "Waiting for MySQL to be ready..."
            sleep 3
          done

      - name: Create test database
        run: |
          mysql -h 127.0.0.1 -u root -p${{ secrets.DB_PASS }} -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_NAME }};"

      - name: Install dependencies
        run: npm install

      # If you have a build step (for example, building a React front-end), add it here.
      # - name: Build
      #   run: npm run build

      - name: Run integration tests
        env:
          DB_NAME: ${{ secrets.DB_NAME }}        # airscan_db
          DB_USER: ${{ secrets.DB_USER }}        # admin
          DB_PASS: ${{ secrets.DB_PASS }}        # admin123
          DB_HOST: ${{ secrets.DB_HOST }}        # localhost
          DB_PORT: ${{ secrets.DB_PORT }}        # 3306
          PORT: ${{ secrets.PORT }}              # 80
          JWT_SECRET: ${{ secrets.JWT_SECRET }}  # (your long secret key)
        run: |
          # This step will:
          # 1) Connect to MySQL with the provided credentials.
          # 2) (Your server’s startup logic—via syncDatabase() and seedDatabase()—will create and seed tables.)
          # 3) Run your integration tests.
          npm test
