name: Run Tests on Push

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root123
          MYSQL_DATABASE: airscan_dbb   # The database name you want to use
        ports:
          - 3306:3306
        options: >
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -proot123"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            mysqladmin ping -h127.0.0.1 -uroot -proot123 --silent && echo "MySQL is ready!" && break
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
        env:
          # Override the environment variables so your app connects 
          # to the GitHub Actions MySQL service instead of your local .env
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASS: root123
          DB_NAME: airscan_dbb
          DB_PORT: 3306

          # Make sure JWT_SECRET is also set to something valid
          JWT_SECRET: "some-super-secret-for-ci-tests"
