name: MySQL Workflow
on: [push]
jobs:
  mysql_job:
    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_PASSWORD: root123
    steps:
      - name: Install MySQL and configure root
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '$MYSQL_ROOT_PASSWORD'; FLUSH PRIVILEGES;"
          sudo systemctl restart mysql
      - name: Create database
        run: sudo mysql -e "CREATE DATABASE IF NOT EXISTS airscan_dbb;"
      - name: Show databases
        run: mysql --protocol=TCP -h 127.0.0.1 -u root -p${MYSQL_ROOT_PASSWORD} -e "SHOW DATABASES;"
