name: MySQL Service Workflow
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root123
          MYSQL_DATABASE: airscan_dbb
        ports:
          - 3306:3306
    steps:
      - run: mysql -h127.0.0.1 -uroot -proot123 -e "SHOW DATABASES;"
