name: Run Tests on Push
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root123
          MYSQL_DATABASE: airscan_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -proot123"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            mysqladmin ping -h127.0.0.1 -uroot -proot123 --silent && echo "MySQL is ready!" && break
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
        env:
          # Override the environment variables so your app connects 
          # to the GitHub Actions MySQL service instead of your local .env
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASS: root123
          DB_NAME: airscan_db
          DB_PORT: 3306

          # Make sure JWT_SECRET is also set to something valid
          JWT_SECRET: "51c941cdbeeaag3f2cc1e5d6e4b2ae5129951b2b354b75db6feb979303c85f4e992d0b4220cf32a58a698b3d96081149712842cf4e4c12754300de7d5b0d4d887b6e8d977987487d1c7355cc2336020b46aee948bfa4f84067c30be127fb7e88679f984c7691f8853d2622b9b1a27e1ba9d9ef1eae58d1761c88b00756448fa66655dfc19ffd430cbf11fc49674a18877f532a00fb34a5be2b5a9482bb9c0863186157332a5d00d837a829339ed2d0421ad1a358b9be021228e945c6cf4696f5e29a756e675832bf26043bb9330ccdd2d60454588efb32eeb9989bc305ed64b877f4dfdab6552b76074e514c5b4c7f51bea490a6499f366a7fd5f15a84ee8f217"
