name: Clean Database

on:
  push:

jobs:
  clean-db:
    if: ${{ github.event.inputs.confirm == 'YES' }}
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASS }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Wait for MySQL to be ready
        run: |
          until mysql -h 127.0.0.1 -u root -p${{ secrets.DB_PASS }} -e "SELECT 1" ; do
            echo "Waiting for MySQL..."
            sleep 3
          done

      - name: WARNING - Destructive Operation
        run: echo "WARNING - This job is going to drop and recreate your database! Do not run in production environments!"

      - name: Drop and recreate database
        run: |
          mysql -h 127.0.0.1 -u root -p${{ secrets.DB_PASS }} -e "DROP DATABASE IF EXISTS \`${{ secrets.DB_NAME }}\`;"
          mysql -h 127.0.0.1 -u root -p${{ secrets.DB_PASS }} -e "CREATE DATABASE \`${{ secrets.DB_NAME }}\`;"

      - name: Verify database reset
        run: |
          RESULT=$(mysql -h 127.0.0.1 -u root -p${{ secrets.DB_PASS }} -e "SHOW DATABASES LIKE '${{ secrets.DB_NAME }}';" | grep ${{ secrets.DB_NAME }})
          if [ -z "$RESULT" ]; then
            echo "Database was not recreated successfully."
            exit 1
          else
            echo "Database emptied and recreated successfully."
          fi

  warn:
    if: ${{ github.event.inputs.confirm != 'YES' }}
    runs-on: ubuntu-latest
    steps:
      - name: Abort Operation
        run: echo "Database cleaning not confirmed. To proceed, re-run and type YES for the confirm input."
